# review-epubmaker向けの設定ファイルの例。
# yamlファイルをRe:VIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: the-androidstudio-book
# 書名
booktitle: 「Android Studioではじめる 簡単Androidアプリ開発」補足資料
# 著者
aut: 有山 圭二
#prt: keiji.io
prt_url:  https://github.com/keiji/the-androidstudio-book
#edt: 有山圭二
date: 2015/01/01
rights: |
  本文書は、有山圭二の著作物であり、クリエイティブコモンズ2.1の表示—非営利—改変禁止ライセンスの元で提供しています。
description: 
# 以下はオプション
# prt: 出版社
# asn: Associated name
# ant: Bibliographic antecedent
# clb: 貢献者
# edt: 編集者
# dsr: デザイナ
# ill: イラストレータ
# pht: 撮影者
# trl: 翻訳者
# date: 刊行日
# rights: 権利表記
# description: ブックの説明
#
# coverfile: カバーページのbody要素内に挿入する内容を記述したファイル名
#coverfile: _cover.html
# coverimage: 表紙用画像ファイル
#coverimage: cover.jpg
# 固有IDに使用するドメイン
urnid: http://gihyo.jp/book/2014/978-4-7741-6998-9
# CSSファイル (yamlファイルおよびRe:VIEWファイルを置いたディレクトリにあること
stylesheet: style.css
# 目次として抽出するレベル
toclevel: 2
# セクション番号を表示するレベル
secnolevel: 3
# review-compileに渡すパラメータ
params: --stylesheet=style.css
# 目次生成用？
mytoc: true
# 奥付生成用
colophon: true
texstyle: reviewmacro
pubhistory: |
  1.0 対応版
debug: false
